### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by yoshikazu-ishitsuka** [yoshikazu-ishitsuka/furima-29350#11]
#### 自身のフリマアプリのURL
- URL: https://furima-29350.herokuapp.com/

#### Basic認証のIDとパスワード
- user: admin
- password: 2222
#### 出品者用のメールアドレスとパスワード
- address: test@test.com
- password: 111aaa
- name: furima太郎
#### 購入者用のメールアドレスとパスワード
- address: test2@test.com
- password: 111aaa
- name: furima二郎
#### 購入用カードの番号・期限・セキュリティコード
- カード番号: 4242424242424242
- 有効期限: （未来）自分は主に「12/24」か「3/23」のどちらかを使用していました
- セキュリティコード: 123

**Comment by mo1015** [comment]
石塚さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます:tada:
おめでとうございます！
**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**

**Comment by yoshikazu-ishitsuka** [comment]
完了済み
